### ISSUE TITLE
01:24:53 [vite] Internal server error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by thisVioletHydra** [hudochenkov/postcss-sorting#106]
## pre
only `postcss-sorting` ruined my `vite` compiler, if i delete postcss-sort config, everything starts working well

## conf `postcss.config.ts`
```ts
import pSorting from 'postcss-sorting';

...

 pSorting({
      order: ['custom-properties', 'dollar-variables', 'declarations', 'at-rules', 'rules'],
      'properties-order': [
        'content',
        'display',
        'background',
        'background-image',
        'background-color',
        'width',
        'height',
        'margin',
        'padding',
        'border',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'transform',
        'cursor',
      ],
      'unspecified-properties-position': 'bottom',
    }),
```

## terminal
```q
01:25:58 [vite] Internal server error: Cannot read properties of undefined (reading 'length')
      at memoizedBinarySearch (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:9993:25)
      at traceSegmentInternal (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:10100:17)
      at originalPositionFor$1 (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:10086:23)
      at formatError (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41476:54)
      at TransformContext.error (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at Object.transform (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41688:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///D:/WWW/blitz-admin-web/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)


```

**Comment by thisVioletHydra** [comment]
hm some libs create conflict =\
```
import pHtml from 'postcss-html';
import loadConfig from 'postcss-load-config';
import pPresetEnv from 'postcss-preset-env';
import safeParser from 'postcss-safe-parser';
import pSyntax from 'postcss-syntax';
import cssVariables from 'postcss-css-variables';
```

**Comment by thisVioletHydra** [comment]
`postcss-font-magician` ruined ALL , closed
