### ISSUE TITLE
Error: module.js:339

### ISSUE THREAD

**Issue by peterleger** [hudochenkov/postcss-sorting#46]
The settings in **v2.0.0** (default and user) are updated to:

```
{
    "order": [
        "custom-properties",
        "dollar-variables",
        "declarations",
        "at-rules",
        {
            "type": "at-rule",
            "name": "include"
        },
        {
            "type": "at-rule",
            "name": "include",
            "parameter": "icon"
        },
        "rules"
    ],
    "properties-order": [
        {
            "emptyLineBefore": true,
            "properties": [
                "margin",
                "padding"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "border",
                "background"
            ]
        }
    ],
    "unspecified-properties-position": "bottom"
}
```
If I run PostCSS, it throws an **error**:

```
PostCSS Sorting
Error: module.js:339
    throw err;
    ^

Error: Cannot find module './terminal-highlight'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/pl/Library/Application Support/Sublime Text 3/Packages/PostCSS Sorting/node_modules/postcss/lib/css-syntax-error.js:15:26)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
How can this be solved?

**Comment by breams** [comment]
How did you solve this? I'm getting the same error.

**Comment by hudochenkov** [comment]
There was a problem with style sheet itself, I suppose. But what was it, @peterleger?

**Comment by hudochenkov** [comment]
@breams what is your style sheet?

**Comment by peterleger** [comment]
@breams, @hudochenkov  I didn't solve it. It is an issue within Sublime Text 3. So I opened up a new issue [here](https://github.com/hudochenkov/sublime-postcss-sorting/issues).

**Comment by breams** [comment]
Ok, I will join that thread.
